/**
 * RuleForge 规则注入模块
 * 将本地规则库中的规则同步到约定文件，供 AI 上下文读取
 *
 * 1.0 方案：写入 .ruleforge/rules.md（Markdown 格式）
 * AI 助手通过读取该文件获取项目编码规则
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs/promises';
import { RuleForgeEngine, RuleYAML } from '@ruleforge/core';
import { RuleForgeConfig } from '../config/ruleforge-config';

/**
 * 规则注入器
 */
export class RuleInjector {
  private engine: RuleForgeEngine;
  private config: RuleForgeConfig;
  private workspaceRoot: string;
  private outputChannel?: vscode.OutputChannel;

  constructor(
    engine: RuleForgeEngine,
    config: RuleForgeConfig,
    workspaceRoot: string,
    outputChannel?: vscode.OutputChannel
  ) {
    this.engine = engine;
    this.config = config;
    this.workspaceRoot = workspaceRoot;
    this.outputChannel = outputChannel;
  }

  /**
   * 从规则库同步到约定文件
   * 读取 .ruleforge/rules/ 下所有 YAML 规则，生成 rules.md
   */
  async syncToConventionsFile(): Promise<boolean> {
    try {
      const rulesDir = this.config.getRulesDir();
      const rules = await this.loadRulesFromDir(rulesDir);

      if (rules.length === 0) {
        this.log('规则库为空，跳过同步');
        return false;
      }

      const content = this.generateRulesMarkdown(rules);
      const targetPath = this.config.getInjectionFilePath();

      // 确保目录存在
      await fs.mkdir(path.dirname(targetPath), { recursive: true });

      // 写入文件
      await fs.writeFile(targetPath, content, 'utf-8');
      this.log(`已同步 ${rules.length} 条规则到 ${targetPath}`);

      return true;
    } catch (error) {
      this.log(`规则同步失败: ${error}`, 'warn');
      return false;
    }
  }

  /**
   * 获取当前生效的规则上下文（供外部调用）
   */
  async getActiveContext(): Promise<string> {
    const rulesDir = this.config.getRulesDir();
    const rules = await this.loadRulesFromDir(rulesDir);

    if (rules.length === 0) {
      return '';
    }

    return this.generateRulesMarkdown(rules);
  }

  /**
   * 从规则库目录加载所有 YAML 规则
   */
  private async loadRulesFromDir(rulesDir: string): Promise<RuleYAML[]> {
    const rules: RuleYAML[] = [];

    try {
      const files = await fs.readdir(rulesDir);
      const yamlFiles = files.filter(
        (f) => f.endsWith('.yaml') || f.endsWith('.yml')
      );

      for (const file of yamlFiles) {
        try {
          const filePath = path.join(rulesDir, file);
          const content = await fs.readFile(filePath, 'utf-8');
          const yaml = await import('js-yaml');
          const rule = yaml.default.load(content) as RuleYAML;

          // 基础验证：必须有 meta 和 rule 字段
          if (rule && rule.meta && rule.rule) {
            rules.push(rule);
          }
        } catch (error) {
          this.log(`加载规则文件失败: ${file} - ${error}`, 'warn');
        }
      }
    } catch (error) {
      if (isNodeError(error) && error.code !== 'ENOENT') {
        this.log(`读取规则目录失败: ${error}`, 'warn');
      }
    }

    return rules;
  }

  /**
   * 生成 Markdown 格式的规则文件
   */
  private generateRulesMarkdown(rules: RuleYAML[]): string {
    const lines: string[] = [];

    lines.push('# Project Coding Rules');
    lines.push('');
    lines.push('> Auto-generated by RuleForge. Do not edit manually.');
    lines.push('> These rules are extracted from development sessions to guide AI coding assistance.');
    lines.push('');

    // 按语言分组
    const byLanguage = new Map<string, RuleYAML[]>();
    for (const rule of rules) {
      const langs = rule.compatibility?.languages || ['unknown'];
      for (const lang of langs) {
        if (!byLanguage.has(lang)) {
          byLanguage.set(lang, []);
        }
        byLanguage.get(lang)!.push(rule);
      }
    }

    // 通用规则（跨语言）
    const universalRules = rules.filter(
      (r) => !r.compatibility?.languages || r.compatibility.languages.length > 1
    );
    if (universalRules.length > 0) {
      lines.push('## General Rules');
      lines.push('');
      for (const rule of universalRules) {
        lines.push(this.formatRuleMarkdown(rule));
      }
    }

    // 按语言输出
    for (const [lang, langRules] of byLanguage) {
      if (lang === 'unknown') continue;
      lines.push(`## ${lang.charAt(0).toUpperCase() + lang.slice(1)} Rules`);
      lines.push('');
      for (const rule of langRules) {
        lines.push(this.formatRuleMarkdown(rule));
      }
    }

    lines.push('');
    lines.push('---');
    lines.push(`*Generated at: ${new Date().toISOString()} | Total rules: ${rules.length}*`);

    return lines.join('\n');
  }

  /**
   * 格式化单条规则为 Markdown
   */
  private formatRuleMarkdown(rule: RuleYAML): string {
    const lines: string[] = [];

    lines.push(`### ${rule.meta.name}`);
    lines.push('');

    if (rule.meta.description) {
      lines.push(`${rule.meta.description}`);
      lines.push('');
    }

    // 触发条件
    if (rule.rule.trigger) {
      lines.push(`**Trigger**: \`${rule.rule.trigger.pattern}\``);
      if (rule.rule.trigger.file_types && rule.rule.trigger.file_types.length > 0) {
        lines.push(` | **Files**: ${rule.rule.trigger.file_types.join(', ')}`);
      }
      lines.push('');
    }

    // 条件
    if (rule.rule.conditions && rule.rule.conditions.length > 0) {
      lines.push('**Conditions**:');
      for (const cond of rule.rule.conditions) {
        const prefix = cond.negated ? '- ❌' : '- ✅';
        lines.push(`${prefix} \`${cond.condition}\``);
      }
      lines.push('');
    }

    // 建议
    if (rule.rule.suggestions && rule.rule.suggestions.length > 0) {
      lines.push('**Suggestions**:');
      for (const sug of rule.rule.suggestions) {
        lines.push(`- ${sug.description}`);
        if (sug.code) {
          lines.push('```');
          lines.push(sug.code);
          lines.push('```');
        }
        if (sug.command) {
          lines.push(`  Run: \`${sug.command}\``);
        }
      }
      lines.push('');
    }

    // 置信度
    const confidence = Math.round(rule.confidence * 100);
    lines.push(`*Confidence: ${confidence}%*`);
    lines.push('');

    return lines.join('\n');
  }

  /**
   * 输出日志
   */
  private log(message: string, level: 'info' | 'warn' = 'info'): void {
    const prefix = level === 'warn' ? '⚠️' : 'ℹ️';
    const logMessage = `[RuleInjector] ${prefix} ${message}`;

    if (this.outputChannel) {
      this.outputChannel.appendLine(logMessage);
    }
    console.log(logMessage);
  }
}

/**
 * 判断是否为 Node.js 系统错误
 */
function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}

export default RuleInjector;
